apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: marketplace-local
  namespace: argocd
spec:
  description: Local Argo CD project for Minikube workloads.
  sourceRepos:
    - https://github.com/oxrod/collector-shop.git
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
