# Bootstrap Minikube for local development.
# Run from repo root: .\infra\k8s\minikube-bootstrap.ps1
#
# Secrets (db-credentials, keycloak-credentials) and ConfigMaps
# (postgres-init, prometheus-config) are now generated by Kustomize
# via secretGenerator/configMapGenerator in the overlay kustomization.yaml.
# No manual creation needed -- just run: kubectl apply -k infra/k8s/overlays/dev

$ErrorActionPreference = "Stop"

Write-Host "All secrets and ConfigMaps are managed by Kustomize."
Write-Host "Deploy with: kubectl apply -k infra/k8s/overlays/dev"
