apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketplace-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - marketplace.local
        - dev.marketplace.local
        - staging.marketplace.local
      secretName: marketplace-tls
  rules:
    - host: marketplace.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80