apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: marketplace/backend
    newName: ghcr.io/oxrod/collector-shop/backend-dev
    newTag: latest
  - name: marketplace/frontend
    newName: ghcr.io/oxrod/collector-shop/frontend-dev
    newTag: latest
  - name: marketplace/fraud-service
    newName: ghcr.io/oxrod/collector-shop/fraud-service-dev
    newTag: latest
  - name: marketplace/notification-service
    newName: ghcr.io/oxrod/collector-shop/notification-service-dev
    newTag: latest
  - name: marketplace/keycloak
    newName: ghcr.io/oxrod/collector-shop/keycloak-dev
    newTag: latest

secretGenerator:
  - name: db-credentials
    literals:
      - username=marketplace
      - password=marketplace_secret
    options:
      disableNameSuffixHash: true
  - name: keycloak-credentials
    literals:
      - admin-password=admin
    options:
      disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
